"""update_threat_intel_schema

Revision ID: 109b01c75102
Revises: 5bff0ff486e8
Create Date: 2026-01-27 20:39:30.286685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '109b01c75102'
down_revision: Union[str, Sequence[str], None] = '5bff0ff486e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_intel_results', sa.Column('risk_score', sa.String(), nullable=False))
    op.add_column('threat_intel_results', sa.Column('confidence', sa.String(), nullable=False))
    op.add_column('threat_intel_results', sa.Column('signals', sa.JSON(), nullable=False))
    op.add_column('threat_intel_results', sa.Column('tags', sa.JSON(), nullable=False))
    op.drop_column('threat_intel_results', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_intel_results', sa.Column('score', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('threat_intel_results', 'tags')
    op.drop_column('threat_intel_results', 'signals')
    op.drop_column('threat_intel_results', 'confidence')
    op.drop_column('threat_intel_results', 'risk_score')
    # ### end Alembic commands ###