"""add_passive_summary_to_scans

Revision ID: 3c2603478c19
Revises: 4fad05831450
Create Date: 2026-01-27 12:59:34.557375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2603478c19'
down_revision: Union[str, Sequence[str], None] = '4fad05831450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('passive_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'passive_summary')
    # ### end Alembic commands ###
