"""add_scan_execution_fields

Revision ID: 42d62c0b2752
Revises: 71ca2748713d
Create Date: 2026-01-26 08:14:11.220843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42d62c0b2752'
down_revision: Union[str, Sequence[str], None] = '71ca2748713d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('tool', sa.String(), nullable=False))
    op.add_column('scans', sa.Column('result_path', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scans', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('scans', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('scans', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('scans', 'created_at')
    op.drop_column('scans', 'result_path')
    op.drop_column('scans', 'tool')
    # ### end Alembic commands ###
