"""add_scan_output

Revision ID: 44740160d195
Revises: 42d62c0b2752
Create Date: 2026-01-26 12:38:00.364013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44740160d195'
down_revision: Union[str, Sequence[str], None] = '42d62c0b2752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('output', sa.Text(), nullable=True))
    op.add_column('scans', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'error')
    op.drop_column('scans', 'output')
    # ### end Alembic commands ###
