"""add risk correlation fields to scan

Revision ID: 589228242a48
Revises: 28dd6b681a86
Create Date: 2026-02-02 19:10:16.344043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589228242a48'
down_revision: Union[str, Sequence[str], None] = '28dd6b681a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('risk_summary', sa.JSON(), nullable=True))
    op.add_column('scans', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('risk_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'risk_level')
    op.drop_column('scans', 'risk_score')
    op.drop_column('scans', 'risk_summary')
    # ### end Alembic commands ###
