"""add_targets_generic

Revision ID: 71ca2748713d
Revises: e4c92ac0c4e9
Create Date: 2026-01-25 21:43:32.671731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ca2748713d'
down_revision: Union[str, Sequence[str], None] = 'e4c92ac0c4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('value', sa.String(), nullable=False))
    op.alter_column('targets', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_targets_project_id'), 'targets', ['project_id'], unique=False)
    op.drop_column('targets', 'domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_targets_project_id'), table_name='targets')
    op.alter_column('targets', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('targets', 'value')
    # ### end Alembic commands ###
