"""add_threat_summary_to_scans

Revision ID: a5be7ccf6a38
Revises: 109b01c75102
Create Date: 2026-01-27 21:13:59.946216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5be7ccf6a38'
down_revision: Union[str, Sequence[str], None] = '109b01c75102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('threat_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'threat_summary')
    # ### end Alembic commands ###