"""add_scan_profile_and_nullable_fields

Revision ID: c17943186673
Revises: 227e2b14d0fd
Create Date: 2026-02-10 14:08:52.109607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17943186673'
down_revision: Union[str, Sequence[str], None] = '227e2b14d0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'profile')
    # ### end Alembic commands ###
