"""add_scan_current_phase

Revision ID: da91d372f13a
Revises: c17943186673
Create Date: 2026-02-10 14:44:34.736380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da91d372f13a'
down_revision: Union[str, Sequence[str], None] = 'c17943186673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('current_phase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'current_phase')
    # ### end Alembic commands ###
